# Generated by Django 5.2.6 on 2026-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('muy_usado', 'Muy Usado'), ('a_retirar', 'A retirar')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('articulo', 'Artículo')], max_length=20)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('editorial', models.CharField(max_length=100)),
                ('autor', models.ManyToManyField(related_name='publicaciones', to='publicaciones.autor')),
                ('unidades', models.ManyToManyField(related_name='publicaciones', to='publicaciones.unidad')),
            ],
        ),
    ]
