# Generated by Django 5.2.6 on 2026-01-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=100)),
                ('devuelto', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='publicaciones.unidad')),
            ],
        ),
    ]
